### ISSUE TITLE
Requiring ansible modules/adhoc command to record cisco ucs manager critical alerts,major faults

### ISSUE THREAD

**Issue by vivekanand552** [CiscoUcs/ucsm-ansible#134]
Hello All,

We are currently automating the Cisco UCS infrastructure environment in our company and we are exploring options to record the critical alerts,major faults in cisco ucs environment before proceeding with automation activities

In the Cisco UCS CLI we have an option to check the critical alerts/major faults under scope monitoring/show new faults that will show new faults.

Can you kindly help with similar ansible modules or ansible adhoc commands to show critical alerts/major faults which can be used as reference that the automation activity has been successfully completed.

Thanks for your help in advance!

Regards
Vivekanand

**Comment by Hlibovytskyi** [comment]
Hi @vivekanand552 
We are using https://github.com/CiscoUcs/ucsm-ansible for that
This example shows how you can easily access UCSm fault instance which contains all faults:
```
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Faults query 
    vars:
      login_info: &login_info
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"  
        
    ucs_query:
      <<: *login_info
      class_ids: Faultinst
    register: Faultinst_query
```
Faultinst_query contains dict with all faults and you can store it in a file or parse directly using ansible.
