### ISSUE TITLE
Not able to delete ldap provider

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm-ansible#26]
**Run a playbook containing task to create ldap provider -**
```
tasks:
    - name: ldap provider create case1
          cisco_ucs_ldap_provider:
          name: 10.65.183.73
          order: 2
          rootdn: CN=Administrator,CN=Users,DC=qatcslab,DC=cisco,DC=com
          basedn: DC=qatcslab,DC=cisco,DC=com
          port: 400
          enable_ssl: yes
          filter: CN=$userid
          attribute: CiscoAVPair
          key: abcd
          timeout: 40
          vendor: MS-AD
          retries: 2
          state: present
          ucs_ip: "{{ ucs_ip }}"
          ucs_username: "{{ ucs_username }}"
          ucs_password: "{{ ucs_password }}"
```

Now delete the same ldap provider -
```
tasks:
    - name: ldap provider create case1
          cisco_ucs_ldap_provider:
          name: 10.65.183.73
          order: 2
          rootdn: CN=Administrator,CN=Users,DC=qatcslab,DC=cisco,DC=com
          basedn: DC=qatcslab,DC=cisco,DC=com
          port: 400
          enable_ssl: yes
          filter: CN=$userid
          attribute: CiscoAVPair
          key: abcd
          timeout: 40
          vendor: MS-AD
          retries: 2
          state: absent
          ucs_ip: "{{ ucs_ip }}"
          ucs_username: "{{ ucs_username }}"
          ucs_password: "{{ ucs_password }}"
```

**Observation**:
The ldap provider does not get deleted
