### ISSUE TITLE
Adding efi boot device to boot policy in legacy mode does not do anything but the output shows changed=1 instead of changed=0

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsm-ansible#30]
When try to add `efi` device to boot policy which is in `legacy mode`, the module does not throw the error and `changed` is shown as `1` instead of `0`.

**Create policy with boot mode as `legacy` -** 
```
tasks:
    - name: boot policy create
      cisco_ucs_boot_policy:
        name: 'boot_policy1'
        state: present
        ucs_ip: "{{ ucs_ip }}"
        ucs_username: "{{ ucs_username }}"
        ucs_password: "{{ ucs_password }}"
```

**Set the boot order and add `efi` as boot device -** 
```
- name: add boot device efi for legacy mode
      cisco_ucs_boot_order:
        name: boot_policy1
        devices:
          - {device_name: efi, device_order: 10}
        ucs_ip: "{{ ucs_ip }}"
        ucs_username: "{{ ucs_username }}"
        ucs_password: "{{ ucs_password }}"
```

**Observed output -** 
```
PLAY [ucs] ************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [ucs_emulator]

TASK [add boot device efi for legacy mode] ****************************************************************************
changed: [ucs_emulator]

PLAY RECAP ************************************************************************************************************
ucs_emulator               : ok=2    changed=1    unreachable=0    failed=0
```
