### ISSUE TITLE
Let ucs_dns take in multiple DNS servers

### ISSUE THREAD

**Issue by vallard** [CiscoUcs/ucsm-ansible#36]
Currently the DNS module only allows one DNS server, but we would like to allow a list of DNS servers so more than one could be added in a single task, similar to how we do with mac pools.

**Comment by SDBrett** [comment]
You can add multiple DNS servers in a task using `with_items`

```
dns_servers:
  - name: 2.2.2.2
    descr: Ansible managed DNS
    state: present
  - name: 1.1.1.1
    descr: Ansible managed DNS
    state: present

- name: set dns
  cisco_ucs_dns:
    name: "{{item.name}}"
    descr: "{{item.descr}}"
    state: "{{item.state}}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"
  with_items: "{{ dns_servers }}"
```
