### ISSUE TITLE
ucs_vnic_template fails when using a VLAN number as the name

### ISSUE THREAD

**Issue by minimalz** [CiscoUcs/ucsm-ansible#75]
Using the ucs_vlans module I'm able to create a VLAN using a number as the name, for example 100.  Although when adding the same VLAN name 100 to ucs_vnic_template vlans_list I get the following error

The full traceback is:
  File "/tmp/ansible_unspyv/ansible_module_ucs_vnic_template.py", line 271, in main
    child_dn = dn + '/if-' + vlan['name']

setup error: cannot concatenate ''str'' and ''int'' objects '

**Comment by dsoper2** [comment]
Hi,

Can you share the playbook you're using and version of UCSM you're testing with and I'll take a look.

**Comment by minimalz** [comment]
```
---
- name: UCS VLANs
  hosts: lab-tor-ucs
  tasks:
    - name: Configure VLANs
      ucs_vlans:
        hostname: 10.71.254.250
        username: ucspe
        password: ucspe
        state: "{{ item.state }}"
        name: "{{ item.name }}"
        id: "{{ item.id }}"
      with_items: "{{ vlans }}"
    - name: Add VLAN to Fabric A vNIC Template
      ucs_vnic_template:
        hostname: 10.71.254.250
        username: ucspe
        password: ucspe
        name: Fabric-A
        fabric: A
        mtu: 9000
        target: adapter
        template_type: updating-template
        #redundancy_type: none
        vlans_list:
          - name: "{{ item.name }}"
      with_items: "{{ vlans }}"
    - name: Add VLAN to Fabric B vNIC Template
      ucs_vnic_template:
        hostname: 10.71.254.250
        username: ucspe
        password: ucspe
        name: Fabric-B
        fabric: B
        mtu: 9000
        target: adapter
        template_type: updating-template
        #redundancy_type: none
        vlans_list:
          - name: "{{ item.name }}"
      with_items: "{{ vlans }}"
```

Vlans located in group_vars/lab-tor-ucs.  The playbook works fine as long as the name is all alphabetical as is written below.  If I use numbers, for example "name: 100" then it errors out.

```
---
vlans:
  - id: 10
    name: WEB
    state: absent
  - id: 20
    name: APP
    state: absent
  - id: 30
    name: SQL
    state: absent
  - id: 100
    name: TEST
    state: present

```
