### ISSUE TITLE
ucs_vnic_template fails with UCS Platform Emulator 3.1

### ISSUE THREAD

**Issue by minimalz** [CiscoUcs/ucsm-ansible#76]
The UCS platform emulator does not support configuring a "Redundancy Type".  Screenshot linked below.  The ucs_vnic_template module fails as a result.  I've removed all references to redundancy type in the code for testing although is it possible to remove this option as mandatory, therefore the code wouldn't need to be modified in order for the module to work in a lab environment.

https://imgur.com/hDGcd1F

**Comment by dsoper2** [comment]
Just replied on the other issue as well - can you share the playbook you're using and version of UCSM (or UCSPE) being tested?

**Comment by minimalz** [comment]
Playbook below.  I'm using Cisco UCS Platform Emulator version 3.1(2ePE1).  My production UCS managers do have an option for "Redundancy Type", so the module would most likely work, although I need to test all playbooks in the lab before I can move them into production.

```
---
- name: UCS VLANs
  hosts: lab-tor-ucs
  tasks:
    - name: Configure VLANs
      ucs_vlans:
        hostname: 10.71.254.250
        username: ucspe
        password: ucspe
        state: "{{ item.state }}"
        name: "{{ item.name }}"
        id: "{{ item.id }}"
      with_items: "{{ vlans }}"
    - name: Add VLAN to Fabric A vNIC Template
      ucs_vnic_template:
        hostname: 10.71.254.250
        username: ucspe
        password: ucspe
        name: Fabric-A
        fabric: A
        mtu: 9000
        target: adapter
        template_type: updating-template
        #redundancy_type: none
        vlans_list:
          - name: "{{ item.name }}"
      with_items: "{{ vlans }}"
    - name: Add VLAN to Fabric B vNIC Template
      ucs_vnic_template:
        hostname: 10.71.254.250
        username: ucspe
        password: ucspe
        name: Fabric-B
        fabric: B
        mtu: 9000
        target: adapter
        template_type: updating-template
        #redundancy_type: none
        vlans_list:
          - name: "{{ item.name }}"
      with_items: "{{ vlans }}"
```

Vlans located in group_vars/lab-tor-ucs

```
---
vlans:
  - id: 10
    name: WEB
    state: absent
  - id: 20
    name: APP
    state: absent
  - id: 30
    name: SQL
    state: absent
  - id: 100
    name: TEST
    state: present

```
